version: '3'
services:
  microservice-sc-config-server:
    container_name: sc-config-server
    hostname: sc-config-server
    image: 127.0.0.1:5000/springcloud/sc-config-server:0.0.1-SNAPSHOT
    network_mode: host
    ports:
      - 9999:8080
  microservice-sc-eureka-server-1:
    container_name: sc-eureka-server-1
    hostname: sc-eureka-server-1
    image: 127.0.0.1:5000/springcloud/sc-eureka-server:0.0.1-SNAPSHOT
    environment:
      - SERVER_PORT=8080
      - CONFIG_SERVER_HOST=sc-config-server
      - CONFIG_SERVER_PORT=9999
      - EUREKA_SERVER_HOST=sc-eureka-server-2
      - EUREKA_SERVER_PORT=8762
    network_mode: host
    ports:
      - 8761:8080
#  microservice-sc-eureka-server-2:
#    container_name: sc-eureka-server-2
#    hostname: sc-eureka-server-2
#    image: 127.0.0.1:5000/springcloud/sc-eureka-server:0.0.1-SNAPSHOT
#    environment:
#      - SERVER_PORT=8080
#      - CONFIG_SERVER_HOST=sc-config-server
#      - CONFIG_SERVER_PORT=9999
#      - EUREKA_SERVER_HOST=sc-eureka-server-1
#      - EUREKA_SERVER_PORT=8761
#    network_mode: host
#    ports:
#      - 8762:8080
