apiVersion: v1
kind: Service
metadata:
  name: biz-service
  namespace: springcloud-cn
  labels:
    service: biz-service
spec:
  type: NodePort
  selector:
    app: biz-service
  ports:
  - name: http
    port: 8003
    nodePort: 30003
    targetPort: 8080
  clusterIP: 10.96.0.8
  externalIPs:
    - 172.20.231.145
