apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: springcloud-cn
  labels:
    service: config-server
spec:
  type: NodePort
  selector:
    app: config-server
  ports:
  - name: http
    port: 9999
    nodePort: 30999
    targetPort: 8080
  clusterIP: 10.96.0.2
  externalIPs:
    - 172.20.231.145
