apiVersion: v1
kind: ReplicationController
metadata:
  name: eureka-server-1
  namespace: springcloud-cn
  labels:
    app: eureka-server
    peer: "1"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
        peer: "1"
    spec:
      containers:
      - name: eureka-server
        image: 127.0.0.1:5000/springcloud/sc-eureka-server:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 2Gi
        env:
          - name: PROFILE
            value: "default"
          - name: SERVER_PORT
            value: "8080"
          - name: CONFIG_SERVER_HOST
#            value: "172.20.231.145"
            value: "config-server"
          - name: CONFIG_SERVER_PORT
            value: "9999"
          - name: EUREKA_SERVER_HOST
            value: "eureka-server-2"
          - name: EUREKA_SERVER_PORT
            value: "8762"
          - name: JAVA_OPTS
            value: "
-server \
-XX:+PrintGCDetails \
-XX:+PrintTenuringDistribution \
-XX:+PrintGCTimeStamps \
-XX:+HeapDumpOnOutOfMemoryError \
-XX:HeapDumpPath=/ \
-Xloggc:/gc.log \
-XX:+UseGCLogFileRotation \
-XX:NumberOfGCLogFiles=5 \
-XX:GCLogFileSize=10M"
        ports:
          - name: http
            containerPort: 8080
