apiVersion: v1
kind: Service
metadata:
  name: eureka-server-1
  namespace: springcloud-cn
  labels:
    service: eureka-server-svc
spec:
  type: NodePort
  selector:
    app: eureka-server
    peer: "1"
  ports:
  - name: http
    port: 8761
    nodePort: 30761
    targetPort: 8080
  clusterIP: 10.96.0.3
  externalIPs:
    - 172.20.231.145
