apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: springcloud-cn
  labels:
    service: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - name: http
    port: 8000
    nodePort: 30000
    targetPort: 8080
  clusterIP: 10.96.0.5
  externalIPs:
    - 172.20.231.145
