kubectl apply -f config-server-rc.yml
kubectl apply -f config-server-svc.yml
kubectl apply -f eureka-server-1-rc.yml
kubectl apply -f eureka-server-1-svc.yml
kubectl apply -f eureka-server-2-rc.yml
kubectl apply -f eureka-server-2-svc.yml
kubectl apply -f gateway-rc.yml
kubectl apply -f gateway-svc.yml
kubectl apply -f spring-admin-rc.yml
kubectl apply -f spring-admin-svc.yml
kubectl apply -f biz-service-rc.yml
kubectl apply -f biz-service-svc.yml
