apiVersion: v1
kind: Service
metadata:
  name: spring-admin
  namespace: springcloud-cn
  labels:
    service: spring-admin
spec:
  type: NodePort
  selector:
    app: spring-admin
  ports:
  - name: http
    port: 8002
    nodePort: 30002
    targetPort: 8080
  clusterIP: 10.96.0.7
  externalIPs:
    - 172.20.231.145
