apiVersion: v1
kind: Service
metadata:
  name: turbine
  namespace: springcloud-cn
  labels:
    service: turbine
spec:
  type: NodePort
  selector:
    app: turbine
  ports:
  - name: http
    port: 8001
    nodePort: 30001
    targetPort: 8080
  clusterIP: 10.96.0.6
  externalIPs:
    - 172.20.231.145
