mybatis:
  #    type-aliases-package: cn.rongcapital.mc2.rulemanager.mapper
  config-location: classpath:mybatis-config.xml
spring:
  data:
    mongodb:
      host: 172.20.231.145 # mongodb的连接地址
      port: 27017 # mongodb的连接端口号
      database: admin # mongodb的连接的数据库
  datasource:
    url: jdbc:mysql://172.20.231.145:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ndadmin
    password: ndadmin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
    maxLifetime: 1765000
    maximumPoolSize: 15
